### ISSUE TITLE
Resource Files Download

### ISSUE THREAD

**Issue by jebbbbb** [PShocker/sdlMS#2]
Are you able to post the resource files from the QQ group somewhere else? I wanted to check this project out but I am not able to use QQ outside of China.

**Comment by PShocker** [comment]
so where can i post the resource files?-_-

**Comment by jebbbbb** [comment]
That is a good question.... I think if you put it on a Chinese file upload site that has a public link I should be able to get to it.

Otherwise, here are some western file sites. Not sure if they will work for you:
https://ufile.io/
https://www.file.io/
https://app.mediafire.com/myfiles


Sorry for the trouble!

**Comment by PShocker** [comment]
i upload to ufile and the url is:
https://ufile.io/vbepdd14

**Comment by jebbbbb** [comment]
Got it. Thanks!

**Comment by yanli-china** [comment]
Hi, can you update the resource link of https://ufile.io/vbepdd14 ? It's expired.
